-- PostgreSQL Schema for the Low-Latency Trading Platform
-- This schema is designed for durability and auditability.
--
-- As of migration 0004 (2026-09), this file matches the live database's
-- `orders`/`trades`/`trade_legs` columns, verified by direct introspection
-- rather than assumed. Apply 0001-0004 in order against a fresh database
-- to reproduce it. Not captured here (out of scope for the GreekSoft
-- reconciler/ACID work that produced this reconciliation): the paper-
-- trading `sim_orders`/`sim_fills`/`sim_positions` tables and
-- `contract_master_raw` (see migrations/0003_contract_master_raw.sql),
-- both of which already exist live but aren't part of the real-money
-- order/fill path this schema documents.

-- Stores broker session details and tokens.
CREATE TABLE broker_sessions (
    id SERIAL PRIMARY KEY,
    broker TEXT NOT NULL,
    user_id TEXT NOT NULL,
    session_token TEXT,
    session_state TEXT, -- e.g., 'LOGGED_IN', 'DISCONNECTED'
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(broker, user_id)
);

-- Master table for all tradable instruments.
CREATE TABLE contracts (
    id SERIAL PRIMARY KEY,
    broker_token BIGINT NOT NULL,
    exchange TEXT NOT NULL,
    symbol TEXT NOT NULL,
    instrument_type TEXT NOT NULL, -- 'FUT', 'OPT', 'EQ'
    expiry_date DATE,
    strike_price NUMERIC(12, 2),
    option_type TEXT, -- 'CE', 'PE'
    lot_size INTEGER NOT NULL,
    tick_size NUMERIC(10, 4) NOT NULL,
    raw_details JSONB, -- Store the raw payload from broker
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(broker_token, exchange)
);
CREATE INDEX idx_contracts_symbol ON contracts(symbol);

-- Defines a trading strategy and its configuration.
CREATE TABLE strategies (
    id SERIAL PRIMARY KEY,
    strategy_name TEXT NOT NULL UNIQUE,
    config JSONB NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Represents a single, unique trade instance.
CREATE TABLE trades (
    id SERIAL PRIMARY KEY,
    trade_uid TEXT NOT NULL UNIQUE,
    strategy_id INTEGER REFERENCES strategies(id),
    symbol TEXT NOT NULL,
    status TEXT NOT NULL, -- e.g., 'PENDING', 'ACTIVE', 'CLOSED'
    config JSONB,
    realized_pnl NUMERIC(15, 2) DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    closed_at TIMESTAMPTZ,
    user_id TEXT,
    broker_name TEXT,
    account_id TEXT
);
CREATE INDEX idx_trades_status ON trades(status);
CREATE INDEX idx_trades_account_id ON trades(account_id);
CREATE INDEX idx_trades_broker_account ON trades(broker_name, account_id);

-- Represents a single leg of a trade (e.g., the CE or PE leg of a straddle).
-- UNIQUE(trade_id, contract_id) is enforced at the DB level (added in
-- migration 0004) because more than one writer (execution-gateway and the
-- reconciler) can race to create a trade's first leg row concurrently.
CREATE TABLE trade_legs (
    id SERIAL PRIMARY KEY,
    trade_id INTEGER NOT NULL REFERENCES trades(id),
    contract_id INTEGER NOT NULL REFERENCES contracts(id),
    target_quantity BIGINT NOT NULL,
    current_quantity BIGINT NOT NULL DEFAULT 0,
    avg_entry_price NUMERIC(12, 2),
    avg_exit_price NUMERIC(12, 2),
    realized_pnl NUMERIC(15, 2) DEFAULT 0,
    status TEXT NOT NULL, -- 'OPEN', 'CLOSED'
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(trade_id, contract_id)
);

-- Stores every order intent generated by a strategy worker.
--
-- broker_order_id (GreekSoft's "gorderid") is deliberately NOT unique:
-- exchange/broker order numbers are only unique within a single trading
-- day and are recycled across days (confirmed against live data -- the
-- same gorderid has legitimately belonged to unrelated trades on
-- different dates). Any code correlating an incoming broker push to an
-- order row by broker_order_id must scope the lookup by trading day
-- (e.g. WHERE broker_order_id = $1 AND created_at::date = $2), not treat
-- it as a global key.
CREATE TABLE orders (
    id SERIAL PRIMARY KEY,
    intent_id TEXT UNIQUE, -- Can be null for orders not originating from an intent
    trade_id INTEGER REFERENCES trades(id), -- Can be null for external orders
    broker_order_id TEXT, -- NOT globally unique -- see comment above
    exchange_order_id TEXT, -- broker's "eorderid"; also only unique per trading day
    contract_id INTEGER NOT NULL REFERENCES contracts(id),
    side TEXT NOT NULL, -- 'BUY', 'SELL'
    quantity BIGINT NOT NULL,
    order_type TEXT NOT NULL, -- 'LIMIT', 'MARKET'
    limit_price NUMERIC(12, 2),
    status TEXT NOT NULL, -- 'CREATED', 'SUBMITTED', 'FILLED', 'REJECTED', etc.
    raw_broker_request JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    order_uid TEXT,
    trade_uid TEXT,
    broker_name TEXT,
    account_id TEXT,
    filled_qty BIGINT NOT NULL DEFAULT 0,
    pending_qty BIGINT NOT NULL DEFAULT 0,
    avg_fill_price NUMERIC(15, 4) NOT NULL DEFAULT 0,
    average_price NUMERIC(12, 4),
    phase TEXT NOT NULL DEFAULT 'PRIMARY',
    hedge_group_id TEXT,
    parent_trade_uid TEXT
);
CREATE INDEX idx_orders_status ON orders(status);
CREATE INDEX idx_orders_broker_order_id ON orders(broker_order_id);
CREATE INDEX idx_orders_account_id ON orders(account_id);
CREATE INDEX idx_orders_trade_uid ON orders(trade_uid);
CREATE INDEX idx_orders_trade_created ON orders(trade_uid, created_at);
CREATE INDEX idx_orders_hedge_group ON orders(hedge_group_id);
CREATE INDEX idx_orders_parent_phase ON orders(parent_trade_uid, phase, status);

-- A log of every state change for an order.
CREATE TABLE order_events (
    id SERIAL PRIMARY KEY,
    order_id INTEGER NOT NULL REFERENCES orders(id),
    status TEXT NOT NULL,
    reason_text TEXT,
    event_timestamp TIMESTAMPTZ NOT NULL,
    raw_broker_response JSONB
);

-- Stores every fill received from the broker.
CREATE TABLE fills (
    id SERIAL PRIMARY KEY,
    order_id INTEGER NOT NULL REFERENCES orders(id),
    trade_id INTEGER NOT NULL REFERENCES trades(id),
    fill_id TEXT NOT NULL,
    fill_quantity BIGINT NOT NULL,
    fill_price NUMERIC(12, 2) NOT NULL,
    fill_timestamp TIMESTAMPTZ NOT NULL,
    raw_broker_fill JSONB,
    UNIQUE(fill_id, order_id)
);

-- Audit log for all manual operator actions.
CREATE TABLE audit_logs (
    id SERIAL PRIMARY KEY,
    user_id TEXT NOT NULL,
    action TEXT NOT NULL, -- e.g., 'MANUAL_SQUARE_OFF', 'PAUSE_TRADE'
    target_id TEXT NOT NULL, -- e.g., trade_uid
    details JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);