ALTER TABLE orders
ADD COLUMN IF NOT EXISTS filled_qty BIGINT NOT NULL DEFAULT 0;

ALTER TABLE orders
ADD COLUMN IF NOT EXISTS pending_qty BIGINT NOT NULL DEFAULT 0;

ALTER TABLE orders
ADD COLUMN IF NOT EXISTS avg_fill_price NUMERIC(15,4) NOT NULL DEFAULT 0;
