// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: libs/contracts/session/session.proto

package session

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // e.g., "trading" or "market_data"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_libs_contracts_session_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libs_contracts_session_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_libs_contracts_session_session_proto_rawDescGZIP(), []int{0}
}

func (x *GetSessionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionToken  string                 `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Gcid          string                 `protobuf:"bytes,3,opt,name=gcid,proto3" json:"gcid,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // The WebSocket session ID from getFlagValues
	IrisUrl       string                 `protobuf:"bytes,5,opt,name=iris_url,json=irisUrl,proto3" json:"iris_url,omitempty"`       // The full URL for the interactive (Iris) WebSocket
	ApolloUrl     string                 `protobuf:"bytes,6,opt,name=apollo_url,json=apolloUrl,proto3" json:"apollo_url,omitempty"` // The full URL for the market data (Apollo) WebSocket
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`                          // Populated if the session is not available or an error occurred.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionResponse) Reset() {
	*x = GetSessionResponse{}
	mi := &file_libs_contracts_session_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResponse) ProtoMessage() {}

func (x *GetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libs_contracts_session_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return file_libs_contracts_session_session_proto_rawDescGZIP(), []int{1}
}

func (x *GetSessionResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *GetSessionResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetSessionResponse) GetGcid() string {
	if x != nil {
		return x.Gcid
	}
	return ""
}

func (x *GetSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetSessionResponse) GetIrisUrl() string {
	if x != nil {
		return x.IrisUrl
	}
	return ""
}

func (x *GetSessionResponse) GetApolloUrl() string {
	if x != nil {
		return x.ApolloUrl
	}
	return ""
}

func (x *GetSessionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_libs_contracts_session_session_proto protoreflect.FileDescriptor

const file_libs_contracts_session_session_proto_rawDesc = "" +
	"\n" +
	"$libs/contracts/session/session.proto\x12\asession\"'\n" +
	"\x11GetSessionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xd5\x01\n" +
	"\x12GetSessionResponse\x12#\n" +
	"\rsession_token\x18\x01 \x01(\tR\fsessionToken\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04gcid\x18\x03 \x01(\tR\x04gcid\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12\x19\n" +
	"\biris_url\x18\x05 \x01(\tR\airisUrl\x12\x1d\n" +
	"\n" +
	"apollo_url\x18\x06 \x01(\tR\tapolloUrl\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error2Y\n" +
	"\x0eSessionService\x12G\n" +
	"\n" +
	"GetSession\x12\x1a.session.GetSessionRequest\x1a\x1b.session.GetSessionResponse\"\x00B)Z'trading-platform/libs/contracts/sessionb\x06proto3"

var (
	file_libs_contracts_session_session_proto_rawDescOnce sync.Once
	file_libs_contracts_session_session_proto_rawDescData []byte
)

func file_libs_contracts_session_session_proto_rawDescGZIP() []byte {
	file_libs_contracts_session_session_proto_rawDescOnce.Do(func() {
		file_libs_contracts_session_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_libs_contracts_session_session_proto_rawDesc), len(file_libs_contracts_session_session_proto_rawDesc)))
	})
	return file_libs_contracts_session_session_proto_rawDescData
}

var file_libs_contracts_session_session_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_libs_contracts_session_session_proto_goTypes = []any{
	(*GetSessionRequest)(nil),  // 0: session.GetSessionRequest
	(*GetSessionResponse)(nil), // 1: session.GetSessionResponse
}
var file_libs_contracts_session_session_proto_depIdxs = []int32{
	0, // 0: session.SessionService.GetSession:input_type -> session.GetSessionRequest
	1, // 1: session.SessionService.GetSession:output_type -> session.GetSessionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_libs_contracts_session_session_proto_init() }
func file_libs_contracts_session_session_proto_init() {
	if File_libs_contracts_session_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_libs_contracts_session_session_proto_rawDesc), len(file_libs_contracts_session_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_libs_contracts_session_session_proto_goTypes,
		DependencyIndexes: file_libs_contracts_session_session_proto_depIdxs,
		MessageInfos:      file_libs_contracts_session_session_proto_msgTypes,
	}.Build()
	File_libs_contracts_session_session_proto = out.File
	file_libs_contracts_session_session_proto_goTypes = nil
	file_libs_contracts_session_session_proto_depIdxs = nil
}
